project_id = "aerostaraviation"
region     = "us-east1"
service_name = "aerostar-aviation-app"
repository_name = "aerostar-aviation"
image_name = "aerostartaviation"
image_url = "us-east1-docker.pkg.dev/aerostaraviation/aerostar-aviation/aerostartaviation:latest"
