
name: Continuous Integration

on:
  push:
    branches: [ master, develop, staging ]
  pull_request:
    branches: [ master, develop, staging ]

jobs:
  ci:
    name: CI - Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Build application
        run: npm run build

      # Uncomment when you have tests configured
      # - name: Run unit tests
      #   run: npm test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: build-files
          path: dist/
          retention-days: 1
